### ISSUE TITLE
Use QC information now stored in HDF5 files

### ISSUE THREAD

**Issue by johnlees** [johnlees/PopPUNK#100]
Can get length, base composition and number of Ns

**Comment by johnlees** [comment]
All of these arguments look sensible, but continues to grow the argument list. We can either try and deal with this together with #73, or possibly put QC into its own script (I prefer the former).

I think the options for QC should be 'stop' (the default), 'prune' (remove failing sequences and continue), 'none' (keep everything and continue).

**Comment by johnlees** [comment]
I think for length an absolute upper and lower limit makes sense, and for bases a maximum proportion of length. What to do when no limits are put in? Perhaps a default based on sigma. 

We should still try and avoid exposing _too_ many internal options as it gets confusing, and two ways to do the same thing are not likely to be used too much in practise.
I think the expected length should just be the mean/median from the DB (possibly ref DB if querying), rather than a user input

**Comment by nickjcroucher** [comment]
I think expected length is only used when there's an explicit ignore length flag - this might also be useful when using reads, if the estimated lengths are off for some reason. I agree otherwise a mean length should be fine, and sigma should be used by default.

You're right about the proportion of ambiguous bases, that makes more sense. The suggested sigma argument is pointless - I would go with a proportion (10% by default?) and allow an absolute number in case that is preferred.

I am relatively relaxed about the extra arguments, as long as they are intuitively named and simply explained. But I agree that having alternative means of passing the parameters in is sensible.

**Comment by nickjcroucher** [comment]
A thought - does it make sense to QC the database and remove outliers before running the Monte Carlo for random sequences?

**Comment by johnlees** [comment]
I guess that having big outliers in terms of sequence composition could affect this, if there are more than the number of clusters used. On the other hand it means that we'd need to add some form of QC into sketchlib, probably duplicating options from PopPUNK, which I don't really want to do.

It is possible to add/re-calculate the random matches for a database, so I'd prefer that route (either rebuild with just the passing seqs, or run add random after pruning).

**Comment by nickjcroucher** [comment]
The latter is what I was thinking - we have to sketch before the QC is run in PopPUNK, so then we can add the random correction afterwards.

**Comment by johnlees** [comment]
Right, that works! From v1.5.0 onwards you can pass `random_correct = False` to `pp_sketchlib.queryDatabase()` (we need to do this when querying too otherwise there's useless computation, especially for single queries). Then there is the following function:
```
  m.def("addRandom", &addRandomToDb, "Add random match chances into older databases",
        py::arg("db_name"),
        py::arg("samples"),
        py::arg("klist"),
        py::arg("use_rc") = true,
        py::arg("num_threads") = 1);
```
callable as `pp_sketchlib.addRandomToDb()`

**Comment by nickjcroucher** [comment]
Great, thanks for that - working version that passes all tests in 24ce680. Would it be possible to add an option for databases to be created without random matches in the sketchlib python API? They can be deleted in PopPUNK if not, but it might be a generally useful option (I would attempt a PR for sketchlib but local installation of the git repo is tricky, sorry).

**Comment by johnlees** [comment]
Great, can you make it into a PR and I'll take a look?

> Would it be possible to add an option for databases to be created without random matches in the sketchlib python API? They can be deleted in PopPUNK if not, but it might be a generally useful option (I would attempt a PR for sketchlib but local installation of the git repo is tricky, sorry).

That is possible in v1.5 by passing `random_correct = False` to `createDatabase()`. But probably not available to you until I've put it on conda. I'm going to finish https://github.com/johnlees/pp-sketchlib/pull/35 before doing that. As with the last one it's API breaking so I'll need to sync the PopPUNK release as much as possible
