### ISSUE TITLE
genomes are duplicated 

### ISSUE THREAD

**Issue by SilasK** [johnlees/PopPUNK#109]
I don't know if this is intended but the pickle of the database contain each genome twice.

The ouptut of the function `def readPickle(pklName):` returns rlist, and qlist` which have duplicated entries. 
This is for the conda version 2.2 and was not the case for v2.1

**Comment by johnlees** [comment]
If you've just run `--create-db` then `rlist == qlist`. 
Or do you mean there are duplicate entries within those?

What was the difference you saw with v2.1?

**Comment by SilasK** [comment]
Yes, I see duplicates within rlist and qlist. (`rlist == qlist`)

With v 2.1 each genome was present only once in rlist.

**Comment by johnlees** [comment]
Sorry, I think I may have phrased that poorly. `rlist == qlist` is expected.

But do you also mean that there are the duplicates inside one of those lists? If you do `len(set(rlist))` is that the same size as `len(rlist)`? i.e. `rlist = ['a', 'b', 'a']` would be a problem, but `rlist = ['a', 'b', 'c'], qlist = ['a', 'b', 'c']` is not

**Comment by SilasK** [comment]
What I see is that `rlist =qlist = ['a', 'b', 'c', 'a', 'b', 'c']` which I think is wrong.

**Comment by johnlees** [comment]
I have checked with an example on v2.2.0, and get:
```
>>> rlist
['24936_2#10', '24936_2#11', '24936_2#12', '24936_2#13', '24936_2#14', '24936_2#15', '24936_2#2', '24936_2#21', '24936_2#23', '24936_2#27', '24936_2#3', '24936_2#30', '24936_2#32', '24936_2#37', '24936_2#4', '24936_2#44', '24936_2#45', '24936_2#46', '24936_2#47', '24936_2#5', '24936_2#51', '24936_2#52', '24936_2#53', '24936_2#54', '24936_2#60', '24936_2#62', '24936_2#63', '24936_2#64', '24936_2#65', '24936_2#7', '24936_2#71', '24936_2#74', '24936_2#75', '24936_2#76', '24936_2#78', '24936_2#79', '24936_2#83', '24936_2#88', '24936_2#9', '24936_2#90', '24936_2#93', '24936_2#94']
>>> qlist
['24936_2#10', '24936_2#11', '24936_2#12', '24936_2#13', '24936_2#14', '24936_2#15', '24936_2#2', '24936_2#21', '24936_2#23', '24936_2#27', '24936_2#3', '24936_2#30', '24936_2#32', '24936_2#37', '24936_2#4', '24936_2#44', '24936_2#45', '24936_2#46', '24936_2#47', '24936_2#5', '24936_2#51', '24936_2#52', '24936_2#53', '24936_2#54', '24936_2#60', '24936_2#62', '24936_2#63', '24936_2#64', '24936_2#65', '24936_2#7', '24936_2#71', '24936_2#74', '24936_2#75', '24936_2#76', '24936_2#78', '24936_2#79', '24936_2#83', '24936_2#88', '24936_2#9', '24936_2#90', '24936_2#93', '24936_2#94']
>>> rlist == qlist
True
>>> len(set(rlist))
42
>>> len(rlist)
42
```
which is the expected behaviour.
Are you able to provide an example where I can reproduce the bug?

Is this giving you other issues with the run?

**Comment by johnlees** [comment]
I believe this is expected behaviour. Closing the issue, but please reopen if having problems
