### ISSUE TITLE
No module named 'pp_sketchlib'

### ISSUE THREAD

**Issue by EricDeveaud** [johnlees/PopPUNK#113]
Hello Trying to install popunk-2.2.0 in a singularity container

all dependencies hd5py, matplotlib, sklearn, graph-tool, hdbscan, sharedmem pycairo and so on,  are installed 

for test purpose I used 
```
python3 -m pip install --user poppunk
```

the tried to run it:

```
Singularity> ~/.local/bin/poppunk -h 
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Traceback (most recent call last):
  File "/root/.local/bin/poppunk", line 5, in <module>
    from PopPUNK.__main__ import main
  File "/root/.local/lib/python3.8/site-packages/PopPUNK/__main__.py", line 14, in <module>
    import pp_sketchlib
ModuleNotFoundError: No module named 'pp_sketchlib'
```

I then grabbed the 2.2.0 tagged release archive and ran `python3 setup.py install`
NB `rm -rf ~/.local` was done before to not conflict with the installation   

I have to sed  pp_sketchlib import  
`sed -i -e 's|import pp_sketchlib|import PopPUNK.sketchlib as pp_sketchlib|' PopPUNK/*.py`

in order to have a working installation 

best regards

Eric

**Comment by johnlees** [comment]
You will need to have [pp-sketchlib](https://github.com/johnlees/pp-sketchlib) v1.5.1 or higher installed, which is not available through PyPI. The recommended way to install this package is through conda, but see the README there for the full list of installation methods

**Comment by johnlees** [comment]
Note the sed command you've used above will break the package. There is a sketchlib.py file in this package which deals with calls to pp_sketchlib, but pp_sketchlib itself (which is a python extension) still needs to be imported along with this

**Comment by EricDeveaud** [comment]
you may want to update the dependencies section of PopPUNK installation document as pp_sketchlib is not mentionned 

tanks for the information on pp_sketchlib

Eric

**Comment by johnlees** [comment]
Thanks for the feedback Eric - the documentation has gotten quite out of date which I apologise for! We will update it soon
