### ISSUE TITLE
Add lengths to network edges for visualisation

### ISSUE THREAD

**Issue by johnlees** [johnlees/PopPUNK#121]
Would be a good idea for web front end

**Comment by nickjcroucher** [comment]
Would this be worth doing in tandem with #87, or is it a purely a change to visualisation (distances would be recalculated anyway)? Could the sparse matrix of within-strain distances be stored?

**Comment by nickjcroucher** [comment]
A thought that the sparse matrix of within-strain distances would enable lineage calculations to be done, and a PopPIPE-type phylogeny to be constructed very quickly. But on the downside: more hassle.

**Comment by johnlees** [comment]
Was just discussing this with @Danderson123: he is able to get a graph of the assigned component and display it in the browser, but for many components it's fairly uninformative. It might give a better display of the structure if the included edges had their lengths, rather than just the binary assignment, but I'm not sure without trying.

So at the moment I was thinking of it purely as a visualisation option. I think the distances are usually saved anyway, so it would be a case of annotating the edges with them.
