### ISSUE TITLE
ModuleNotFoundError: No module named 'sklearn.neighbors.kde'

### ISSUE THREAD

**Issue by samlipworth** [johnlees/PopPUNK#143]
Just installed poppunk on a new conda env i.e. 

`conda create -n poppunk
conda activate poppunk
conda install -c bioconda poppunk`

No problems with installation but when trying to run..

Get the error:

`ModuleNotFoundError: No module named 'sklearn.neighbors.kde'`

Can't run `poppunk --version` either - same issue.

Any idea what's wrong? Previously ran Poppunk on same machine with no issues.

Thanks

**Comment by johnlees** [comment]
Can you post the results from `conda list` within your environment?

**Comment by samlipworth** [comment]
`# packages in environment at /well/bag/users/lipworth/miniconda3/envs/poppunk:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                      1_llvm    conda-forge
ca-certificates           2020.12.5            ha878542_0    conda-forge
capnproto                 0.6.1                hfc679d8_1    conda-forge
certifi                   2020.12.5        py36h5fab9bb_1    conda-forge
cycler                    0.10.0                     py_2    conda-forge
dbus                      1.13.6               hfdff14a_1    conda-forge
decorator                 4.4.2                      py_0    conda-forge
dendropy                  4.5.1              pyh3252c3a_0    bioconda
expat                     2.2.9                he1b5a44_2    conda-forge
fontconfig                2.13.1            h736d332_1003    conda-forge
freetype                  2.10.4               h7ca028e_0    conda-forge
gettext                   0.19.8.1          h0b5b191_1005    conda-forge
glib                      2.66.4               hcd2ae1e_1    conda-forge
gsl                       2.6                  he838d99_1    conda-forge
gst-plugins-base          1.14.5               h0935bb2_2    conda-forge
gstreamer                 1.18.2               h3560a44_1    conda-forge
hdbscan                   0.8.26           py36ha112f06_3    conda-forge
icu                       68.1                 h58526e2_0    conda-forge
joblib                    1.0.0              pyhd8ed1ab_0    conda-forge
jpeg                      9d                   h36c2ea0_0    conda-forge
kiwisolver                1.3.1            py36h51d7077_0    conda-forge
krb5                      1.17.2               h926e7f8_0    conda-forge
lcms2                     2.11                 hcbb858e_1    conda-forge
ld_impl_linux-64          2.35.1               hea4e1c9_1    conda-forge
libblas                   3.9.0                7_openblas    conda-forge
libcblas                  3.9.0                7_openblas    conda-forge
libclang                  11.0.0          default_ha5c780c_2    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libevent                  2.1.10               hcdb4288_3    conda-forge
libffi                    3.3                  h58526e2_2    conda-forge
libgcc-ng                 9.3.0               h5dbcf3e_17    conda-forge
libgfortran-ng            9.3.0               he4bcb1c_17    conda-forge
libgfortran5              9.3.0               he4bcb1c_17    conda-forge
libglib                   2.66.4               h164308a_1    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
liblapack                 3.9.0                7_openblas    conda-forge
libllvm10                 10.0.1               he513fc3_3    conda-forge
libllvm11                 11.0.0               he513fc3_0    conda-forge
libopenblas               0.3.12          pthreads_h4812303_1    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libpq                     12.3                 h255efa7_3    conda-forge
libstdcxx-ng              9.3.0               h2ae2ef3_17    conda-forge
libtiff                   4.2.0                hdc55705_0    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libwebp-base              1.1.0                h36c2ea0_3    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxkbcommon              1.0.3                he3ba5ed_0    conda-forge
libxml2                   2.9.10               h72842e0_3    conda-forge
llvm-openmp               11.0.0               hfc4b9b4_1    conda-forge
llvmlite                  0.35.0           py36h05121d2_0    conda-forge
lz4-c                     1.9.3                h9c3ff4c_0    conda-forge
mash                      2.2.2                ha61e061_2    bioconda
matplotlib                3.3.3            py36h5fab9bb_0    conda-forge
matplotlib-base           3.3.3            py36he12231b_0    conda-forge
mkl                       2020.4             h726a3e6_304    conda-forge
mysql-common              8.0.22               ha770c72_1    conda-forge
mysql-libs                8.0.22               h1fd7589_1    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
networkx                  2.5                        py_0    conda-forge
nspr                      4.29                 h9c3ff4c_1    conda-forge
nss                       3.60                 hb5efdd6_0    conda-forge
numba                     0.52.0           py36h284efc9_0    conda-forge
numpy                     1.19.5           py36h2aa4a07_0    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openssl                   1.1.1i               h7f98852_0    conda-forge
pandas                    1.1.5            py36h284efc9_0    conda-forge
patsy                     0.5.1                      py_0    conda-forge
pcre                      8.44                 he1b5a44_0    conda-forge
pillow                    8.1.0            py36h4f9996e_0    conda-forge
pip                       20.3.3             pyhd8ed1ab_0    conda-forge
poppunk                   1.1.3                    py36_0    bioconda
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyqt                      5.12.3           py36h5fab9bb_6    conda-forge
pyqt-impl                 5.12.3           py36h7ec31b9_6    conda-forge
pyqt5-sip                 4.19.18          py36hc4f0c31_6    conda-forge
pyqtchart                 5.12             py36h7ec31b9_6    conda-forge
pyqtwebengine             5.12.1           py36h7ec31b9_6    conda-forge
python                    3.6.12          hffdb5ce_0_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.6                     1_cp36m    conda-forge
pytz                      2020.5             pyhd8ed1ab_0    conda-forge
qt                        5.12.9               h9d6b050_2    conda-forge
rapidnj                   2.3.2                hc9558a2_0    bioconda
readline                  8.0                  he28a2e2_2    conda-forge
scikit-learn              0.24.0           py36he4fde30_0    conda-forge
scipy                     1.5.3            py36h9e8f40b_0    conda-forge
setuptools                49.6.0           py36h9880bd3_2    conda-forge
sharedmem                 0.3.6                      py_0    bioconda
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlite                    3.34.0               h74cdb3f_0    conda-forge
statsmodels               0.12.1           py36ha112f06_1    conda-forge
threadpoolctl             2.1.0              pyh5ca1d4c_0    conda-forge
tk                        8.6.10               h21135ba_1    conda-forge
tornado                   6.1              py36h1d69622_0    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge
zstd                      1.4.8                ha95c52a_1    conda-forge
`

**Comment by johnlees** [comment]
Looks like an old version of PopPUNK, you've got v1.1.3. Can you upgrade to the current version (v2.3.0)? If you delete your environment, easiest way might be to recreate with:
```
conda create -c bioconda -n poppunk poppunk==2.3.0
conda activate poppunk 
```

**Comment by samlipworth** [comment]
Yup fixed thanks
