### ISSUE TITLE
terminate called after throwing an instance of 'std::runtrime_error'

### ISSUE THREAD

**Issue by drhoads** [johnlees/PopPUNK#172]
Installed Poppunk in WSL2 and used it many times.  Needed to run some new data and WSL2 suggested to run sudo apt update.  When I was done then poppunk won't finish a run 
$ poppunk --create-db --output SaureusPoultryGenomes --r-files r-list.txt --qc-filter continue --threads 8
'
   terminate called after throwing an instance of 'std::runtrime_error'
   terminate called recursively
   terminate called recursively
   Aborted (core dumped)
Poppunk 2.3.0 sketchlib v1.6.2
I tried reinstalling poppunk and no solution.

**Comment by johnlees** [comment]
This looks like it probably can't find the files listed in r-list.txt, or they don't contain sequence. Could you double-check that? You may want to upgrade sketchlib to v1.7.3 if you can, as that reports this error in a more helpful way.

If that's not it, can you paste the whole output you get from running the command

**Comment by drhoads** [comment]
If I leave out the '--qc-filter continue' then I do get reports saying that certain files contain no sequence, but these are all downloaded directly from NCBI and I can guarantee they all have sequence in them.  I have built blast databases from these same files and completed tblastn searches.  I will try to upgrade sketchlib.

**Comment by drhoads** [comment]
Wait, I figured it out.  Problem is using windows listings for the path to the files.  Silly mistake, I have to convert to Linux format in WSL2.  Stupid me I had the full dos path to the genome files (e.g., e:\DNAwork\Saureus\....), and forgot this is a Linux shell and needed it to be /mnt/e/DNAwork/Saureus/....
Sorry about that.

**Comment by johnlees** [comment]
Ah no problem, I appreciate that the old error message wasn't very clear about this being a data/file access issue!
