### ISSUE TITLE
KeyError when trying to generate combined Microreact output

### ISSUE THREAD

**Issue by nickjcroucher** [johnlees/PopPUNK#24]
Something strange seems to happen when trying to build a combined microreact output. When running the command:

`python3 ./PopPUNK/poppunk-runner.py --assign-query --ref-db mass_ref  --model-dir mass_refined_gmm  --q-files pmen14.list  --output mass_query_pmen14  --full-db --threads 4  --cytoscape --microreact  --rapidnj ./rapidNJ/bin/ --update-db`

I get the error:
 
> Traceback (most recent call last):
>   File "./PopPUNK/poppunk-runner.py", line 9, in <module>
>     main()
>   File "/lustre/scratch118/infgen/team81/nc3/strain_structure/querying_examples/PopPUNK/PopPUNK/__main__.py", line 383, in main
>     outputsForCytoscape(genomeNetwork, isolateClustering, args.output, args.info_csv, ordered_queryList)
>   File "/lustre/scratch118/infgen/team81/nc3/strain_structure/querying_examples/PopPUNK/PopPUNK/plot.py", line 51, in outputsForCytoscape
>     queryList)
>   File "/lustre/scratch118/infgen/team81/nc3/strain_structure/querying_examples/PopPUNK/PopPUNK/plot.py", line 94, in writeClusterCsv
>     if name in clustering['combined']:
> KeyError: 'combined'

The reference database contains these files:

> -rw-r--r-- 1 nc3 team81 49363944 Jun 14 14:00 mass_ref.17.msh
> -rw-r--r-- 1 nc3 team81 24723936 Jun 14 14:00 mass_ref.13.msh
> -rw-r--r-- 1 nc3 team81 49363944 Jun 14 14:00 mass_ref.21.msh
> -rw-r--r-- 1 nc3 team81 49363944 Jun 14 14:00 mass_ref.25.msh
> -rw-r--r-- 1 nc3 team81 49363944 Jun 14 14:04 mass_ref.29.msh
> -rw-r--r-- 1 nc3 team81    44556 Jun 14 14:12 mass_ref.dists.pkl
> -rw-r--r-- 1 nc3 team81  3030848 Jun 14 14:12 mass_ref.dists.npy

The model directory contains these files:

> -rw-r--r-- 1 nc3 team81  269906 Jun 14 17:44 mass_refined_gmm_refined_fit.png
> -rw-r--r-- 1 nc3 team81      22 Jun 14 17:44 mass_refined_gmm_fit.pkl
> -rw-r--r-- 1 nc3 team81     772 Jun 14 17:44 mass_refined_gmm_fit.npz
> -rw-r--r-- 1 nc3 team81    1755 Jun 14 17:44 mass_refined_gmm.refs
> -rw-r--r-- 1 nc3 team81   18569 Jun 14 17:44 mass_refined_gmm_clusters.csv
> -rw-r--r-- 1 nc3 team81 5047704 Jun 14 17:44 mass_refined_gmm.25.msh
> -rw-r--r-- 1 nc3 team81 5047704 Jun 14 17:44 mass_refined_gmm.21.msh
> -rw-r--r-- 1 nc3 team81 5047704 Jun 14 17:44 mass_refined_gmm.17.msh
> -rw-r--r-- 1 nc3 team81 2527704 Jun 14 17:44 mass_refined_gmm.13.msh
> -rw-r--r-- 1 nc3 team81    2541 Jun 14 17:45 mass_refined_gmm_graph.gpickle
> -rw-r--r-- 1 nc3 team81 5047704 Jun 14 17:45 mass_refined_gmm.29.msh

Am I missing something obvious here?

**Comment by johnlees** [comment]
Hmm nothing immediately obvious to me - I'll have a proper look first thing tomorrow!

**Comment by johnlees** [comment]
This will be a bug introduced by changes for #23

**Comment by nickjcroucher** [comment]
Seems to reflect the loading of refined models:

 ```
   def load(self, fit_npz, fit_obj):
        '''Load the model from disk. Called from :func:`~loadClusterFit`

        Args:
            fit_npz (dict)
                Fit npz opened with :func:`numpy.load`
            fit_obj (None)
                The saved fit object (not used)
        '''
        self.optimal_x = np.asscalar(fit_npz['intercept'][0])
        self.optimal_y = np.asscalar(fit_npz['intercept'][1])
        self.core_boundary = np.asscalar(fit_npz['core_acc_intercepts'][0])
        self.accessory_boundary = np.asscalar(fit_npz['core_acc_intercepts'][1])
        self.scale = fit_npz['scale']
        self.fitted = True
        self.indiv_fitted = False # changed here
        self.slope = 2  # should this be fixed?
```
With this change, I get to a different bug (not currently checking for distances being supplied when building a new microreact output - also need to check whether a new distance matrix is calculated between references when the reference database is rebuilt, but these tweaks can wait).

I have also added this section in at line ~356 in __main__.py, but I've not pushed to the repo because I am confident it's quicker for you to identify what needs to change without first working out what I've hacked away at; anyway, I've pasted this here in case it's helpful:

`            # Assign clustering by adding to network
            ordered_queryList, query_distMat = addQueryToNetwork(refList, queryList, args.q_files,
                    genomeNetwork, kmers, queryAssignments, model, args.output, args.no_stream,
                    args.update_db, args.threads, args.mash)

#            isolateClustering = printClusters(genomeNetwork, args.output + "/" + args.output,
#                    old_cluster_file, False)

            print("Mode is indiv fitted:"+str(model.indiv_fitted))
            fit_type = 'combined'

            # Write core and accessory based clusters, if they worked
            if model.indiv_fitted:
                indivNetworks = {}
                for dist_type, slope in zip(['core', 'accessory'], [0, 1]):
                    isolateClustering[dist_type] = printClusters(indivNetworks[dist_type], args.output + "/" + args.output + "_" + dist_type)
                if args.core_only:
                    fit_type = 'core'
                    genomeNetwork = indivNetworks['core']
                elif args.accessory_only:
                    fit_type = 'accessory'
                    genomeNetwork = indivNetworks['accessory']

            isolateClustering = {fit_type: printClusters(genomeNetwork, args.output + "/" + args.output)}`

**Comment by nickjcroucher** [comment]
Thanks! Sorry for leaving you with this, we had another long and unproductive afternoon at the hospital – will try to catch up this evening/weekend.

**Comment by johnlees** [comment]
No problem - it was an easy fix from an error I had introduced. Let me know if there are still problems
