### ISSUE TITLE
error in assign query

### ISSUE THREAD

**Issue by OrsonMM** [johnlees/PopPUNK#29]
Dear team POPPUNK 

I run the comands:

1$ poppunk --create-db --r-files lista2.txt --output strain_db --min-k 15  --k-step 2  --sketch-size 1000000 --threads 7 --plot-fit 5 

2$ poppunk --fit-model --distances strain_db/strain_db.dists --output strain_db --full-db --ref-db strain_db --dbscan --microreact --rapidnj ../../../Programs/rapidNJ/bin/ 

3$ poppunk_references --network strain_db/strain_db_graph.gpickle --ref-db strain_db --distances strain_db/strain_db.dists --model strain_db --output strain_references --threads 7

4$ poppunk --refine-model --distances strain_references/strain_references.dists --output strain_references --full-db --ref-db strain_references --threads 7 --indiv-refine

**5$ poppunk --assign-query --ref-db strain_references --q-files lista_willy.txt --output strain_query --threads 7 --update-db  (Error)**

ubuntu@enteropatogenos:~/Results/willy/poppunk$ poppunk --assign-query --ref-db strain_references --q-files lista_willy.txt --output strain_query --threads 7 --update-db                          /home/ubuntu/.linuxbrew/opt/python/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
PopPUNK (POPulation Partitioning Using Nucleotide Kmers)
Mode: Assigning clusters of query sequences

Creating mash database for k = 15
Random 15-mer probability: 0.00
Creating mash database for k = 17
Random 17-mer probability: 0.00
Creating mash database for k = 19
Random 19-mer probability: 0.00
Creating mash database for k = 21
Random 21-mer probability: 0.00
Creating mash database for k = 23
Random 23-mer probability: 0.00
Creating mash database for k = 25
Random 25-mer probability: 0.00
Creating mash database for k = 27
Random 27-mer probability: 0.00

Creating mash database for k = 29
Random 29-mer probability: 0.00
mash dist -p 7 strain_references/strain_references.15.msh strain_query/strain_query.15.msh 2> strain_references.err.log
mash dist -p 7 strain_references/strain_references.17.msh strain_query/strain_query.17.msh 2> strain_references.err.log
mash dist -p 7 strain_references/strain_references.19.msh strain_query/strain_query.19.msh 2> strain_references.err.log
mash dist -p 7 strain_references/strain_references.21.msh strain_query/strain_query.21.msh 2> strain_references.err.log
mash dist -p 7 strain_references/strain_references.23.msh strain_query/strain_query.23.msh 2> strain_references.err.log
mash dist -p 7 strain_references/strain_references.25.msh strain_query/strain_query.25.msh 2> strain_references.err.log
mash dist -p 7 strain_references/strain_references.27.msh strain_query/strain_query.27.msh 2> strain_references.err.log
mash dist -p 7 strain_references/strain_references.29.msh strain_query/strain_query.29.msh 2> strain_references.err.log
Calculating core and accessory distances
Loading previously refined model
Network loaded: 7 samples
Calculating all query-query distances
mash dist -p 7 strain_query/strain_query.15.msh strain_query/strain_query.15.msh 2> strain_query.err.log
mash dist -p 7 strain_query/strain_query.17.msh strain_query/strain_query.17.msh 2> strain_query.err.log
mash dist -p 7 strain_query/strain_query.19.msh strain_query/strain_query.19.msh 2> strain_query.err.log
mash dist -p 7 strain_query/strain_query.21.msh strain_query/strain_query.21.msh 2> strain_query.err.log
mash dist -p 7 strain_query/strain_query.23.msh strain_query/strain_query.23.msh 2> strain_query.err.log
mash dist -p 7 strain_query/strain_query.25.msh strain_query/strain_query.25.msh 2> strain_query.err.log
mash dist -p 7 strain_query/strain_query.27.msh strain_query/strain_query.27.msh 2> strain_query.err.log
mash dist -p 7 strain_query/strain_query.29.msh strain_query/strain_query.29.msh 2> strain_query.err.log
Calculating core and accessory distances
Updating reference database to strain_query
Creating mash database for k = 15
Random 15-mer probability: 0.00
Overwriting db: strain_query/strain_query.15.msh
Creating mash database for k = 17
Random 17-mer probability: 0.00
Overwriting db: strain_query/strain_query.17.msh
Creating mash database for k = 19
Random 19-mer probability: 0.00
Overwriting db: strain_query/strain_query.19.msh
Creating mash database for k = 21
Random 21-mer probability: 0.00
Overwriting db: strain_query/strain_query.21.msh
Creating mash database for k = 23
Random 23-mer probability: 0.00
Overwriting db: strain_query/strain_query.23.msh
Creating mash database for k = 25
Random 25-mer probability: 0.00
Overwriting db: strain_query/strain_query.25.msh
Creating mash database for k = 27
Random 27-mer probability: 0.00
Overwriting db: strain_query/strain_query.27.msh
Creating mash database for k = 29
Random 29-mer probability: 0.00
Overwriting db: strain_query/strain_query.29.msh
Writing strain_query/strain_query.15.joined.msh...
Writing strain_query/strain_query.17.joined.msh...
Writing strain_query/strain_query.19.joined.msh...
Writing strain_query/strain_query.21.joined.msh...
Writing strain_query/strain_query.23.joined.msh...
Writing strain_query/strain_query.25.joined.msh...
Writing strain_query/strain_query.27.joined.msh...
Writing strain_query/strain_query.29.joined.msh...
Traceback (most recent call last):
  File "/home/ubuntu/.linuxbrew/bin/poppunk", line 11, in <module>
    sys.exit(main())
  File "/home/ubuntu/.linuxbrew/opt/python/lib/python3.6/site-packages/PopPUNK/__main__.py", line 422, in main
    refList, refList_copy, self, ref_distMat = readPickle(args.distances)
  File "/home/ubuntu/.linuxbrew/opt/python/lib/python3.6/site-packages/PopPUNK/utils.py", line 53, in readPickle
    with open(pklName + ".pkl", 'rb') as pickle_file:
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str´|

I hope that you can help me.

**Comment by nickjcroucher** [comment]
Hi - this should be fixed if you add "--distances strain_references/strain_references.dists" to your "--assign-query" command. When updating the database, the distance file also has to be updated accordingly, but we don't check that file is supplied at the moment - I'll change this. Please let us know if this fixes the issue.

**Comment by nickjcroucher** [comment]
Hopefully fixed in ca7507630157b12d205bc33be73366eddd7d98a7.

**Comment by OrsonMM** [comment]
Okay, I'll try. Your recommendation. 

One question more. 

When I finished the assign-query step.
How to generate the.nwk and .csv graphs ? 
What command to use ?, in the manual is not very clear. but I guess with --fit-model or --refine-model in my new strain_query folder with the commands --microreact and --rapidj.

:)

**Comment by nickjcroucher** [comment]
You can add the "--microreact" flag (and "--rapidnj") to the --assign-query command when running it with the "--update-db" option.

**Comment by OrsonMM** [comment]
thank you so much for all  !!!
