### ISSUE TITLE
bioconda package?

### ISSUE THREAD

**Issue by tseemann** [johnlees/PopPUNK#31]
Struggling to get poppunk installed here.

Wondering if you have plans to write a bioconda package for it?

**Comment by johnlees** [comment]
Sounds like a good idea! I'll do that when I get a chance.

Anything I should know about pip difficulties?

**Comment by tseemann** [comment]
I think they usually they prefer you to write conda packages for each python dependency.

Because you have fixed version requirements eg. `dendropy==2.3.0` i couldn't `conda install dendropy==2.3.0` because a pkg for that version doesn't exist in bioconda.

But I'm not a conda expert. I will try making Brew recipe but it's unlikely to ever happen due to the depenendency hell and brew doesn't support environments.

**Comment by tseemann** [comment]
I went to our RHEL 7.5 cluster and installed miniconda3 fresh:

```
wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
bash Miniconda3-latest-Linux-x86_64.sh

source miniconda3/bin/activate

conda config --add channels defaults
conda config --add channels conda-forge
conda config --add channels bioconda

conda install numpy scipy mkl dendropy matplotlib hdbscan networkx numba numpy pandas scikit-learn scipy sharedmem mash

pip install poppunk

poppunk -h

usage: PopPUNK [-h]
               (--easy-run | --create-db | --fit-model | --refine-model | --assign-query)
               [--ref-db REF_DB] [--r-files R_FILES] [--q-files Q_FILES]
               [--distances DISTANCES] --output OUTPUT [--plot-fit PLOT_FIT]
               [--full-db] [--update-db] [--overwrite] [--min-k MIN_K]
               [--max-k MAX_K] [--k-step K_STEP] [--sketch-size SKETCH_SIZE]
               [--K K] [--dbscan] [--D D]
               [--min-cluster-prop MIN_CLUSTER_PROP] [--pos-shift POS_SHIFT]
               [--neg-shift NEG_SHIFT] [--manual-start MANUAL_START]
               [--indiv-refine] [--no-local] [--model-dir MODEL_DIR]
```

**Comment by johnlees** [comment]
https://github.com/bioconda/bioconda-recipes/pull/10951

**Comment by tseemann** [comment]
Noice!
