### ISSUE TITLE
Errors in microreact output with reference-based querying

### ISSUE THREAD

**Issue by nickjcroucher** [johnlees/PopPUNK#35]
Isolate 11657_5#30 is correctly assigned to strain 6_14 in the reference-based (https://microreact.org/project/BkXBGJuFm) and complete (https://microreact.org/project/rJGAHaPtm) query-based clustering. However, it is in the wrong place in the tree and t-SNE projection in the reference-based clustering only. It seems there is a misalignment of names and distances that only applies to the core and accessory distance matrices when querying a reference-based database.

**Comment by johnlees** [comment]
Do you have example command lines and data?

**Comment by nickjcroucher** [comment]
Yep - using OLDYEAR and NEWYEAR as integer shell variables, the command for the full run was:

`poppunk-runner.py  --assign-query --q-files ${NEWYEAR}.list --ref-db BSAC_${OLDYEAR} --model-dir BSAC_refined --distances BSAC_${OLDYEAR}/BSAC_${OLDYEAR}.dists --previous-clustering BSAC_${OLDYEAR} --output BSAC_${NEWYEAR} --full-db --update-db --threads 4 --microreact --info-csv ecoli.csv --overwrite --rapidnj ./rapidNJ/bin/rapidnj;`

For the reference-based analysis:

`poppunk-runner.py  --assign-query --q-files ${NEWYEAR}.list --ref-db BSAC_${OLDYEAR}_ref --model-dir BSAC_refined_ref --distances BSAC_${OLDYEAR}_ref/BSAC_${OLDYEAR}_ref.dists --previous-clustering BSAC_${OLDYEAR}_ref --output BSAC_${NEWYEAR}_ref --update-db --threads 4 --microreact --info-csv ecoli.csv --rapidnj ./bin/rapidnj`

So it should only be "--full-db" that differs between the commands.

**Comment by johnlees** [comment]
Ok thanks, having a look now. First thing I'm wondering is whether it's still fine if `--update-db` is removed

**Comment by johnlees** [comment]
Ah good point, so we can't test that easily. I suspect it's something in that block though.
I've got the commands running, so will take a look in the debugger

**Comment by johnlees** [comment]
Looking through the code I couldn't spot any obvious errors.

When I've tried this using the following command:
```
python ~/installations/strain_assignment/poppunk-runner.py --assign-query --q-files /lustre/scratch118/infgen/team81/nc3/poppunk/e_coli/2002.list --ref-db /lustre/scratch118/infgen/team81/nc3/poppunk/e_coli/BSAC_2001 --model-dir /lustre/scratch118/infgen/team81/nc3/poppunk/e_coli/BSAC_refined --distances /lustre/scratch118/infgen/team81/nc3/poppunk/e_coli/BSAC_2001/BSAC_2001.dists --previous-clustering /lustre/scratch118/infgen/team81/nc3/poppunk/e_coli/BSAC_refined --output BSAC_2002 --full-db --update-db --threads 4 --microreact --info-csv /lustre/scratch118/infgen/team81/nc3/poppunk/e_coli/ecoli.csv --rapidnj rapidnj
```
It looks like it's worked, unless I'm missing something: https://microreact.org/project/r1JO_IKKQ

I'm wondering whether the problem only occurs when the reference database is reference only (i.e. every iteration was run without `--full-db`, which isn't what I used here). I'll have a look at that now.

**Comment by johnlees** [comment]
Yes, looks like this goes wrong when the original db was also run without `--full-db`
https://microreact.org/project/H1Y51vFK7

**Comment by johnlees** [comment]
This is proving tricky to track down.

Cluster assignment is identical in each case.
When I look at the saved distances between these microreacts (the .npy/.pkl file) some of the rows mismatch between the two:
```
> mismatch1[!duplicated(mismatch1)]
 [1] "11657_5#35.contigs_velvet.fa" "11657_5#36.contigs_velvet.fa" "11657_6#31.contigs_velvet.fa"
 [4] "11657_6#34.contigs_velvet.fa" "11658_5#63.contigs_velvet.fa" "11658_5#64.contigs_velvet.fa"
 [7] "11658_6#63.contigs_velvet.fa" "11658_7#51.contigs_velvet.fa" "11679_5#30.contigs_velvet.fa"
[10] "11679_6#24.contigs_velvet.fa" "11679_6#25.contigs_velvet.fa" "11679_7#23.contigs_velvet.fa"
[13] "11679_8#19.contigs_velvet.fa" "11679_8#20.contigs_velvet.fa" "11679_8#33.contigs_velvet.fa"
[16] "11679_8#44.contigs_velvet.fa" "11791_3#15.contigs_velvet.fa" "11791_6#12.contigs_velvet.fa"
[19] "11791_6#16.contigs_velvet.fa" "11791_7#42.contigs_velvet.fa"
> mismatch2[!duplicated(mismatch2)]
 [1] "11657_5#25.contigs_velvet.fa" "11657_5#27.contigs_velvet.fa" "11657_5#30.contigs_velvet.fa"
 [4] "11657_7#29.contigs_velvet.fa" "11657_7#31.contigs_velvet.fa" "11657_7#41.contigs_velvet.fa"
 [7] "11658_3#23.contigs_velvet.fa" "11658_3#24.contigs_velvet.fa" "11658_4#26.contigs_velvet.fa"
[10] "11658_4#27.contigs_velvet.fa" "11658_4#30.contigs_velvet.fa" "11658_4#32.contigs_velvet.fa"
[13] "11658_5#58.contigs_velvet.fa" "11658_5#59.contigs_velvet.fa" "11658_5#61.contigs_velvet.fa"
[16] "11658_6#58.contigs_velvet.fa" "11658_6#60.contigs_velvet.fa" "11658_7#44.contigs_velvet.fa"
[19] "11658_7#60.contigs_velvet.fa" "11679_4#17.contigs_velvet.fa" "11679_4#20.contigs_velvet.fa"
[22] "11679_5#14.contigs_velvet.fa" "11679_5#16.contigs_velvet.fa" "11679_6#21.contigs_velvet.fa"
[25] "11679_7#18.contigs_velvet.fa" "11679_8#13.contigs_velvet.fa" "11679_8#15.contigs_velvet.fa"
[28] "11791_7#37.contigs_velvet.fa"
```

This is some, but not all, of the ref-query comparisons

**Comment by nickjcroucher** [comment]
A suspicion is the saving of the distances - I had to change the code around line 447 in __main__.py:
         
```
                dists_out = args.output + "/" + os.path.basename(args.output) + ".dists"
                if args.full_db is False:
                    # could also have newRepresentativesNames in this diff (should be the same) - but want
                    # to ensure consistency with the network in case of bad input/bugs
                    nodes_to_remove = set(combined_seq).difference(genomeNetwork.nodes)
                    postpruning_combined_seq, newDistMat = prune_distance_matrix(combined_seq, nodes_to_remove, complete_distMat, dists_out)
                    
                    # ensure mash sketch and distMat order match
                    assert postpruning_combined_seq == refList + newQueries

                else:
                    storePickle(combined_seq, combined_seq, True, complete_distMat, dists_out)

                    # ensure mash sketch and distMat order match
                    assert combined_seq == refList + newQueries
```

This is where the distances are saved, using `postpruning_combined_seq` if `--full-db` is omitted; but the microreact distances are generated with the lines below, with `combined_seq`:

```
            # generate outputs for microreact if asked
            if args.microreact:
                sys.stderr.write("Writing microreact output\n")
                outputsForMicroreact(combined_seq, core_distMat, acc_distMat, isolateClustering, args.perplexity,
                                     args.output, args.info_csv, args.rapidnj, ordered_queryList, args.overwrite)

```
Without this change, the distance matrices and names didn't match up in terms of their length; however, maybe the order is still wrong somehow?

**Comment by johnlees** [comment]
The order of sample names written out to the pickle when pruning references is (usually slightly) inconsistent with the order in the mash files. Fixing this now

Hopefully this hasn't affected too much in the paper - I guess we didn't really use `--assign-query` without `--full-db` much, but it might be worth checking fig 5C again

**Comment by nickjcroucher** [comment]
Great, thanks for being much faster than me at identifying this - I'll re-run the E. coli analysis, and if that looks OK, I'll re-run the pneumo searches.

**Comment by johnlees** [comment]
Looking good now: https://microreact.org/project/HkHdsFqFQ
