### ISSUE TITLE
Please help me 

### ISSUE THREAD

**Issue by OrsonMM** [johnlees/PopPUNK#36]
ubuntu@vibrio:~$ poppunk -h
/home/ubuntu/.linuxbrew/opt/python/lib/python3.7/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
usage: PopPUNK [-h]
               (--easy-run | --create-db | --fit-model | --refine-model | --assign-query)
               [--ref-db REF_DB] [--r-files R_FILES] [--q-files Q_FILES]
               [--distances DISTANCES]
               [--external-clustering EXTERNAL_CLUSTERING] --output OUTPUT
               [--plot-fit PLOT_FIT] [--full-db] [--update-db] [--overwrite]
               [--min-k MIN_K] [--max-k MAX_K] [--k-step K_STEP]
               [--sketch-size SKETCH_SIZE] [--K K] [--dbscan] [--D D]
               [--min-cluster-prop MIN_CLUSTER_PROP] [--pos-shift POS_SHIFT]
               [--neg-shift NEG_SHIFT] [--manual-start MANUAL_START]
               [--indiv-refine] [--no-local] [--model-dir MODEL_DIR]
               [--previous-clustering PREVIOUS_CLUSTERING] [--core-only]
               [--accessory-only] [--microreact] [--cytoscape] [--phandango]
               [--grapetree] [--rapidnj RAPIDNJ] [--perplexity PERPLEXITY]
               [--info-csv INFO_CSV] [--mash MASH] [--threads THREADS]
               [--no-stream] [--version]

How i can install a old library for poppunk using pip. 

thank you

**Comment by johnlees** [comment]
I'm not sure what problem you are having (looks like it's running ok) -- could you describe in more detail?
The message is a warning that a feature in scikit-learn will be removed in future, and won't affect the run or results

It is possible to use older versions, though we wouldn't recommend it.
