### ISSUE TITLE
Integrate generate_microreact.py script

### ISSUE THREAD

**Issue by johnlees** [johnlees/PopPUNK#44]
The script at `scripts/generate_microreact.py` should be integrated as an exported command in the main package to avoid duplicating functions.

Additionally, the following should be fixed:
* Use of rapidnj isn't supported (function definition not included)
* `--output` isn't clear if it is a prefix/directory/file, and fails if a folder with that name does not exist

**Comment by johnlees** [comment]
The dists.csv file should also be removed

**Comment by nickjcroucher** [comment]
Added the "--generate-viz" mode to start to address this with update 873f3178011c23fa71105be0e63bc5dd3c695cee. This should allow a subset of data to be extracted and visualised as well. I condensed some of the functions within __main__.py, looks like this may have caused a problem according to the travis checks.

**Comment by johnlees** [comment]
Great, thanks! Working on sorting out the problems now

**Comment by nickjcroucher** [comment]
Two issues cropping up with my code. First, there's a problem with the Cytoscape output file:

`Building phylogeny
Running t-SNE
Writing phandango output
Copying microreact treeWriting grapetree output
Using microreact treeWriting cytoscape output
Traceback (most recent call last):
  File "./PopPUNK/poppunk-runner.py", line 10, in <module>
    main()
  File "/lustre/scratch118/infgen/team284/nc3/transmission/PopPUNK/PopPUNK/PopPUNK/__main__.py", line 466, in main
    outputsForCytoscape(genomeNetwork, isolateClustering, args.output, args.info_csv)
  File "/lustre/scratch118/infgen/team284/nc3/transmission/PopPUNK/PopPUNK/PopPUNK/plot.py", line 388, in outputsForCytoscape
    queryList)
  File "/lustre/scratch118/infgen/team284/nc3/transmission/PopPUNK/PopPUNK/PopPUNK/plot.py", line 534, in writeClusterCsv
    pd.DataFrame(data=d).to_csv(outfile, columns = colnames, index = False)
`
Second, there combined clusters being output to the microreact CSV just read "set()". Which appears problematic.

I'll try to have a look at what's going on here.

**Comment by nickjcroucher** [comment]
To complete the error for Cytoscape above, the final line is:

`KeyError: "None of [['id', 'combined_Cluster']] are in the [columns]"`

**Comment by johnlees** [comment]
I should update the travis-CI to do more thorough checks soon, as we've had a few regressions now as features have been added.

First thought on the cytoscape error (might be the same in phandango and grapetree outputs) is that it might be the graph passed needing to be a dict with `graph['combined'] = <graph>` vs just a <graph>

**Comment by nickjcroucher** [comment]
Microreact, Phandango and Grapetree all completed, albeit with the weird "set()" clustering, it only fell over on the Cytoscape output.

**Comment by nickjcroucher** [comment]
Fixed in b07ebc21a51a0838d893c91f39d96ca497fa4e12.

**Comment by johnlees** [comment]
Ah, didn't realise this was specific to the `--generate-viz` mode. Obviously I didn't check what the `readClusters()` function actually did! Surprised it got that far at all. Thanks for fixing!
