### ISSUE TITLE
Can't fit the model for Salmonella Enteritidis

### ISSUE THREAD

**Issue by apredeus** [johnlees/PopPUNK#53]
Hello John, 

thank you for a very interesting tool. I'm trying to fit a model for about ~ 3000 genomes of specific Salmonella serovar (Enteritidis). Problem is, it seems, that its pangenome is not that diverse, and model fit does quite terribly. Default settings (K=2) produced fit with score of 0.0604. Refinement failed with no error message, and DBSCAN also just fails. Fitting model with K=3 generates the following parameters; however, it identifies 82 clusters which seems excessive? 

> Fit summary:
> 	Avg. entropy of assignment	0.0060
> 	Number of components used	3
> 
> Scaled component means:
> 	[0.06682449 0.18523007]
> 	[0.0311445  0.06276067]
> 	[0.59918419 0.36938257]
> 
> Warning: trying to create very large network
> Network summary:
> 	Components	82
> 	Density	0.4531
> 	Transitivity	0.8935
> 	Score	0.4887

I'd appreciate any advice on how to get it to work. Thank you! I've attached the accessory/core genome plot. 

![image](https://user-images.githubusercontent.com/7825825/67123455-442cbc80-f1e8-11e9-932b-5d5ab0114f76.png)

**Comment by nickjcroucher** [comment]
Hi Alex,

Based on the distribution, it might be worth trying a higher K with the 2D Gaussian (e.g. K=10), although DBSCAN would probably be better – is there any error message when DBSCAN fails? Have you tried altering the DBSCAN parameters? Looking at the distribution, it may be worth refining the model in the core only mode (--indiv-refine).

Nick.

**Comment by apredeus** [comment]
Hello Nick, 

thank you for your reply. All I get (aside from some deprecation warnings) is the message 

>Failed to find distinct clusters in this dataset

Are there any other options to use on the model fit stage? I'm getting the same error for the selection of Typhimuriums I'm processing.

**Comment by nickjcroucher** [comment]
Hi Alex,

You can try altering the constraints on the DBSCAN fit (judging from the distribution, increasing --min-cluster-prop might be helpful):

Model fit options:
  --K K                 Maximum number of mixture components [default = 2]
  --dbscan              Use DBSCAN rather than mixture model
  --D D                 Maximum number of clusters in DBSCAN fitting [default
                        = 100]
  --min-cluster-prop MIN_CLUSTER_PROP
                        Minimum proportion of points in a cluster in DBSCAN
                        fitting [default = 0.0001]

Perhaps the best approach would be to add in other Salmonella genomes – even a small number of representatives of other serotypes should serve as effective outgroups in the analysis, and shouldn’t increase the runtime much.

**Comment by apredeus** [comment]
I've tried adding 20 Typhimurium genomes, and dbscan still fails. I think the isolates are too close to each other, and that's probably what's causing it. My sample fits seem to confirm it - most have very high proportion of matches. It would be good to try a bigger k-mer but seems like anything above 29 is not supported by mash? 

![image](https://user-images.githubusercontent.com/7825825/67235368-dc23e380-f43e-11e9-8ce5-be31bf137826.png)

**Comment by nickjcroucher** [comment]
You can increase the sketch size to get a more precise measurement of divergence between closely-related isolates - maybe up 10 fold?
________________________________

**Comment by johnlees** [comment]
Looking at the original plot I think this should be possible with a GMM or refined fit, but possibly with some tweaking. I would certainly try stepping up through values of ``--K`` to start with.

**Comment by johnlees** [comment]
Going to close this, but do reopen if more problems arise
