### ISSUE TITLE
Using external clustering for generate-viz and beyond?

### ISSUE THREAD

**Issue by nickjcroucher** [johnlees/PopPUNK#55]
I've edited the code to allow the external clustering CSV to be used in the generate-viz mode - I was wondering whether the external clustering should be the default file used in this mode (and querying) if present?

Also, should we validate the external clustering against the network?

**Comment by johnlees** [comment]
Cool, thanks! I'll take a look through soon, but I did notice the tests were failing:
https://dev.azure.com/jlees/PopPUNK/_build/results?buildId=13&view=logs&jobId=19c563d8-3dcd-57d1-cd5e-9dd946b0a29b&taskId=4292cd33-74e4-56d2-4fed-99bb1e6ffbb8&lineStart=221&lineEnd=228&colStart=1&colEnd=60

```
Traceback (most recent call last):
  File "../poppunk-runner.py", line 10, in <module>
    main()
  File "/home/vsts/work/1/s/PopPUNK/__main__.py", line 441, in main
    isolateClustering = {'combined': readClusters(cluster_file, return_dict=True, ext_clust=True)}
  File "/home/vsts/work/1/s/PopPUNK/utils.py", line 172, in readClusters
    (sample, clust_id, hist) = line.rstrip().split(",")
ValueError: not enough values to unpack (expected 3, got 2)
```

I think having it as the default if provided makes sense, as to get the poppunk clusters one can simply omit that option (and we don't need to add another command line flag).

I think external clusters are not necessarily consistent with the network? iirc multiple external can be assigned to each input?

**Comment by nickjcroucher** [comment]
Problem fixed in cf916b459218493d10fab6621cff1655a0b2b245 - I just simplified the parsing and ignored any historical merging of clusters for the moment. It would probably be good to work out how to retain and update this information though.

For the external clustering, my thought was what the default should be when querying against a directory containing both "_assignment_clusters.csv" and "_assignment_external_clusters.csv"?

**Comment by johnlees** [comment]
Ah I see – I think using the PopPUNK clusters as default would be best, as external clusters can be added on at the end in either mode

**Comment by johnlees** [comment]
Are there any more code changes needed to implement this (I can go ahead and make those), or can this be closed?

**Comment by nickjcroucher** [comment]
I'm not sure whether the external_clusters is the default at the moment? Other than that, it seems to work as expected.

**Comment by johnlees** [comment]
I think external_clusters is used instead if provided, which I think is the behaviour I'd expect given the command line options, and allows both clusters to be used (making it the default in all cases would make using the poppunk ones harder)
