### ISSUE TITLE
Where does pip install the scripts/

### ISSUE THREAD

**Issue by tseemann** [johnlees/PopPUNK#56]
Looking for https://poppunk.readthedocs.io/en/latest/scripts.html

Does `pip3 install poppunk` install these somewhere?

**Comment by johnlees** [comment]
Hi Torsten,

Sorry for the slow reply. No, I haven't set up either `pip` or `conda` to install the scripts as of the current version. 
In the next release I'll update the installers to include them, but for now to get them you'll have to clone the repository.

Cheers,
John

**Comment by tseemann** [comment]
Colleagues were doing the tutorial etc and came up against this roadblock. 
Thanks for replying,.

**Comment by johnlees** [comment]
These have now been added (I hope) and documented on the scripts page: https://poppunk.readthedocs.io/en/latest/scripts.html

**Comment by tseemann** [comment]
Any chance they will be added to the `pip` manifest so they end up in `bin/` folder?
And maybe rename them to have prefix `poppunk-_______` ?

**Comment by johnlees** [comment]
I believe that's exactly what I did in 7677d72 and 83b1a623c525c42be935f3463a11f395e9d4b8b9. If this isn't working correctly let me know, or feel free to make a PR to fix it

**Comment by tseemann** [comment]
Are those commits in pipy though?

**Comment by johnlees** [comment]
Hoping that conda automatically picks these up with its version bump too!
