### ISSUE TITLE
Limitations to input size

### ISSUE THREAD

**Issue by jimmyliu1326** [johnlees/PopPUNK#57]
If I am interested in identifying stable clusters from ~100,000 genomes, would there be any complications in analyzing them in a single run? Or would you recommend dividing the inputs into batches of 10,000 genomes, constructing an initial reference database, and subsequently updating the database with each batch?

**Comment by johnlees** [comment]
10^5 might be a bit ambitious with the current code, which scales with N^2. I would agree with your suggestion of iterative updates instead.

10^4 as an initial set is definitely doable (and you can check your fit, other errors without committing loads of computing time). A random subsample should work.
Then using assign query mode to deal with the remaining batches.

Let us know if you run into any issues!
