### ISSUE TITLE
How to extract within-strain and between-strain mean vaule of core and accessory distance?

### ISSUE THREAD

**Issue by YangChaoCN** [johnlees/PopPUNK#58]
Hi John,

Thank you for the very useful tool!

I want to know how to extract within-strain and between-strain mean vaule of core and accessory distance, in the figure *.refined_fit.png, we can see the numers, but how to get them or output these numbers into a text?

Best,
Chao

**Comment by johnlees** [comment]
Hi Chao,

This was also raised in an older issue https://github.com/johnlees/PopPUNK/issues/45, and I believe I added this in https://github.com/johnlees/PopPUNK/commit/1541ec3b2a119230b8f62c0d763142a4aa954c3d.

So if you have v1.1.6 or higher, these should get printed to the terminal (they are the centres of the mixture model fit). The latest version is 1.2.2, and you can upgrade with `conda upgrade poppunk` if installed this way.

Alternatively, you can write the distances out to file and calculate means yourself:
https://poppunk.readthedocs.io/en/latest/scripts.html#writing-the-pairwise-distances-to-an-output-file

Or you can look at the model file in an interactive python session:
```
python
>>> import numpy as np
>>> fit_data = np.load("listeria_db_new_fit.npz")
>>> fit_data['means']
array([[ 0.95457929,  0.90355727],
       [ 0.12138537,  0.25473795],
       [ 0.20826142,  0.40180672],
       [ 0.00826465,  0.0732244 ]])
>>> fit_data['scale']
array([ 0.04537197,  0.37147789])
```

The centres on the plot are given by `means * scale`

**Comment by YangChaoCN** [comment]
Hi John,
Thanks for your quick response.

1) I'm using PopPUNK 1.2.2 and  saw the "Scaled component means" in stderr, but not the scale value, where is it? I can get the scale in interactive python session, but how to get the non-scaled distance, in you example above:
0.95457929*0.04537197. 0.90355727*0.37147789 , like this?

2) the results of "Scaled component means" looks like a range (am I right?, and what's the meaning of each row? ), I want to get the mean vaule, what should I do?
3) I can output the pairwise distance using the scripts (extract_distances.py), then calculated the mean distance, is this the between-strain mean distanse? how to get the within-strain mean distance using the distance dataset?

here's my stderr:
PopPUNK (POPulation Partitioning Using Nucleotide Kmers)
Mode: Creating clusters from assemblies (create_db & fit_model)
Creating mash database for k = 21
Random 21-mer probability: 0.00
Creating mash database for k = 25
Random 25-mer probability: 0.00
Creating mash database for k = 29
Random 29-mer probability: 0.00
mash dist -p 20 Vibrio-vulnificus-4/Vibrio-vulnificus-4.21.msh Vibrio-vulnificus-4/Vibrio-vulnificus-4.21.msh 2> Vibrio-vulnificus-4.err.log
mash dist -p 20 Vibrio-vulnificus-4/Vibrio-vulnificus-4.25.msh Vibrio-vulnificus-4/Vibrio-vulnificus-4.25.msh 2> Vibrio-vulnificus-4.err.log
mash dist -p 20 Vibrio-vulnificus-4/Vibrio-vulnificus-4.29.msh Vibrio-vulnificus-4/Vibrio-vulnificus-4.29.msh 2> Vibrio-vulnificus-4.err.log
Calculating core and accessory distances
Fit summary:
	Number of clusters	5
	Number of datapoints	15225
	Number of assignments	110999643

Scaled component means
	[0.00556794 0.06878311]
	[0.8124708  0.76914094]
	[0.31965789 0.44406021]
	[0.5893881  0.70929047]
	[0.49303013 0.63414118]

Initial model-based network construction based on DBSCAN fit
Initial boundary based network construction
Decision boundary starts at (0.35,0.48)
Trying to optimise score globally
Trying to optimise score locally

Optimization terminated successfully;
The returned value satisfies the termination criteria
(using xtol =  1e-05 )
Network summary:
	Components	94
	Density	0.0156
	Transitivity	0.9956
	Score	0.9800
Removing 81 sequences
Creating mash database for k = 21
Random 21-mer probability: 0.00
Overwriting db: Vibrio-vulnificus-4/Vibrio-vulnificus-4.21.msh
Creating mash database for k = 25
Random 25-mer probability: 0.00
Overwriting db: Vibrio-vulnificus-4/Vibrio-vulnificus-4.25.msh
Creating mash database for k = 29
Random 29-mer probability: 0.00
Overwriting db: Vibrio-vulnificus-4/Vibrio-vulnificus-4.29.msh
Done

Best,
Chao

**Comment by johnlees** [comment]
1. Yes, you can only get the scale from the interactive python session (as the scaled means are what you need for setting a `--manual-start`). Multiplying them is correct as you state, but you can just do this in python/numpy if you want
2. Scaled component means aren't a range, they are x-y (core-accessory) co-ordinates in the columns. The rows are the components estimated by the mixture model, so there will be up to `--K` of these. In cases where K > 2, the within-strain component is the one which is closest to the origin, between-strain is the one with the highest weight
3. This is a bit more tricky and would require some programmatic fiddling based on the current poppunk code, but I think will give you exactly what you are after. You will need to combine these output rows with their within/between assignments.

For 3), I would do this as follows:
* Run a debugging session with your poppunk command line `python -m pdb poppunk-runner.py <options>`
* Add a breakpoint at this line: https://github.com/johnlees/PopPUNK/blob/master/PopPUNK/__main__.py#L332
In this version of the code you would type something like `b __main__.py:332`
* Run the program to this point by typing `c`
* When it stops, see if you can get the assignments by typing `p assignments`
* If those look ok, write them to a file by typing something like `np.save_txt(assignments, "assignments.txt")`
* Then you would combine these with the distances to get the mean, splitting in two based on the assignment labels (which match up with these rows). 

Possibly easier than the last three steps, when the code gets to this point you could also just run:
```
np.mean(distMat[assignment==model.within_label])
np.mean(distMat[assignment!=model.within_label])
```
