### ISSUE TITLE
Low quality genomes

### ISSUE THREAD

**Issue by susheelbhanu** [johnlees/PopPUNK#61]
Hi, 

Thanks for a great tool. I wanted to test this tool to see similarities in my populations and am running it as follows:

```
poppunk --easy-run --r-files reference_list_updated --output poppunk_output_NewZealand --threads 24 --plot-fit 10 --min-k 15 --full-db

PopPUNK (POPulation Partitioning Using Nucleotide Kmers)
        (with backend: sketchlib v1.1.0)
Mode: Creating clusters from assemblies (create_db & fit_model)
Worst random match probability at 15-mers: 0.00
Sketching 187 genomes using 24 thread(s)
Writing sketches to file
Calculating distances using 24 thread(s)
/home/users/sbusi/apps/miniconda3/envs/poppunk/lib/python3.7/site-packages/PopPUNK/mash.py:660: RuntimeWarning: divide by zero encountered in log
  args=(klist, np.log(pairwise)),
Fitting k-mer curve failed: Residuals are not finite in the initial point.
With mash input [0.0018,0.0002,0.    ,0.0001]
Check for low quality input genomes
```

I have CheckM results elsewhere, but is there a way from the output here to figure out which are the 'low quality' genomes? Alternatively, is there a way to force the tool to run through the low quality files?

Thank you for your help!
-Susheel

**Comment by johnlees** [comment]
This looks like an error message from the `--plot-fit` function. Can you try running again removing that option for now?

This also looks like it could well be a problem the k-mer lengths chosen. What genomes are you looking at? You may want to lower the range of k-mer sizes you are looking at, if they are small.
Another problem can be if they are too divergent. Are you looking within a species?

**Comment by susheelbhanu** [comment]
@johnlees Thanks a lot for the prompt help. 

Removing the `--plot-fit` seemed to do the trick. These are populations at the Genus level. I realize that that was not the original intention of the tool, but I wanted to see if it could be applied here. Interestingly enough, I now get the following message:
`Distances failed quality control (change QC options to run anyway)`

Which QC options is this referring to? Is it just the `threshold` or something else, including `distances` and/or others?

Thanks again for your help!
-Susheel

**Comment by nickjcroucher** [comment]
The QC options are `--max-a-dist` and `--ignore-length`: https://github.com/johnlees/PopPUNK/blob/master/docs/options.rst.

It might also be worth trying increasing the sketch size to improve the sensitivity for detecting similarity. Reducing the minimum k-mer length to the lowest it can go while still not risking false positives will likely be the most effective change.

**Comment by susheelbhanu** [comment]
Thanks a lot, @nickjcroucher. 

I'm currently trying out the `--max-a-dist` option. That seems to have forced them to run. I'll try the other also in a bit. I've been using the k-mer `step` option alongside to figure out where the sweet-spot is. 

Thank you again for the quick responses!
