### ISSUE TITLE
cannot fit model 

### ISSUE THREAD

**Issue by pavlo888** [johnlees/PopPUNK#62]
Hi, 

So I am trying to try this promising tool with a set of 99 genomes. I succeeded in generating the database for my genome set. Now I am trying to fit the model by running `poppunk --fit-model --distances strain_db/strain_db.dists --output strains --full-db --ref-db strain_db --K 2` and I get the following error: Distances failed quality control (change QC options to run anyway). 

Could you please help me solve this issue? 

Cheers, 
Pablo

**Comment by johnlees** [comment]
You can try adding `--ignore-distances` and `--max-a-dist 1` to get it to run and produce a distance plot. You will likely have to remove some of your genomes based on what you find, take a look here: https://poppunk.readthedocs.io/en/latest/troubleshooting.html#dealing-with-poor-quality-data
