### ISSUE TITLE
Quickstart tutorial does not work.

### ISSUE THREAD

**Issue by bkille** [johnlees/PopPUNK#63]
Following the directions in the [quickstart tutorial](https://poppunk.readthedocs.io/en/latest/quickstart.html), I get the following error:
```
$ poppunk --easy-run --r-files reference_list.txt --output lm_example --threads 4 --plot-fit 5 --min-k 13 --full-db
PopPUNK (POPulation Partitioning Using Nucleotide Kmers)
	(with backend: sketchlib v1.1.0)
Mode: Creating clusters from assemblies (create_db & fit_model)
Input reference list is misformatted
Must contain sample name and file, tab separated
```

It's easily fixed by just adding a column with the sample names. I think it would be beneficial to allow users to pass in files directly using command line args i.e. `-r-files data/*.fna` and simply use the file names (without the extension) as the sample id's.

**Comment by johnlees** [comment]
Thanks for pointing this out!
This is a new format introduced as of v2 and above. The documentation is due an overhaul to reflect these changes, but I haven't had a chance to do that yet.
For now I've made some quick edits to at least produce correct input in the quickstart and tutorial.
