### ISSUE TITLE
Change k-mer length range?

### ISSUE THREAD

**Issue by nickjcroucher** [johnlees/PopPUNK#65]
With sketchlib rather than mash, could we allow more flexibility over the range of k-mer lengths enabled? Would just involve moving the validation code to the mash-mode only section, but I don't know if there are algorithmic or memory issue asociated with giving users this much freedom?

**Comment by johnlees** [comment]
Yeah in theory it can be anything now. Your commit 3698cadd18f3ed0c7585c0620fadf607336a7861 looks good to me

**Comment by nickjcroucher** [comment]
Great, was just having a look at that for testing - the one concern I had was if a user were to set kmer length longer than reads in an input FASTQ? I suppose it's fine if there's a read count after length filtering?

**Comment by johnlees** [comment]
Any sequences that are shorter than the max k-mer length are removed by sketchlib. If there are no sequences left an error message is given, so I think we should be ok
