### ISSUE TITLE
Parallelise assignment functions

### ISSUE THREAD

**Issue by johnlees** [johnlees/PopPUNK#78]
In `models.py` can do chunks at a time with sharedmem

**Comment by nickjcroucher** [comment]
Possible with numba pthreads, to maintain optimisation of each process? Numba seems to be incompatible with multiprocessing at the moment. I phrase as a question, as I've been trying without anything to hold up as evidence of this being possible.

**Comment by nickjcroucher** [comment]
Functioning example for refined models: 8cb08c9.

**Comment by nickjcroucher** [comment]
Wrong commit - see 513729ad2d26e5d55102408420f6c22f261108c6. Pthreads shares read-only so no good for matrix translation.

**Comment by nickjcroucher** [comment]
Just recording a thought - in models.py, plot re-assigns sampled points - currently not multi-threaded.

**Comment by nickjcroucher** [comment]
Need to think about this with regard to numba: https://numba.pydata.org/numba-doc/latest/user/faq.html.
