### ISSUE TITLE
fitting model needs remove command 

### ISSUE THREAD

**Issue by pavlo888** [johnlees/PopPUNK#85]
Hi, 

I am currently trying to fit a model and I am using the following command: 
`'/home/sam/Downloads/PopPUNK-master/poppunk_prune-runner.py' --fit-model --distances agro_strains_db/agro_strains_db.dists --output agro_strain_db --full-db --ref-db agro_strains_db --dbscan`
And then I get the following error: 
`poppunk_prune: error: the following arguments are required: --remove`

Could you please help me solve this issue? 

Thanks!

**Comment by nickjcroucher** [comment]
You are running `poppunk_prune-runner.py`, rather than `poppunk-runner.py`.

**Comment by pavlo888** [comment]
Right. Sorry. I just realized that. 

Thanks!

**Comment by nickjcroucher** [comment]
No problem, hope it works smoothly now!
