### ISSUE TITLE
GPU accelerated graphs

### ISSUE THREAD

**Issue by johnlees** [johnlees/PopPUNK#87]
Could look at using https://github.com/rapidsai/cugraph

**Comment by johnlees** [comment]
Triangles: `cugraph.community.triangle_count.triangles(G)`
Denominator: `degree = G.degree(); sum([d * (d - 1) for d in degree)`
Transitivity = triangles/denominator
(see https://networkx.org/documentation/stable/_modules/networkx/algorithms/cluster.html#transitivity)

Cliques: https://docs.rapids.ai/api/cugraph/stable/api.html?highlight=degree#module-cugraph.community.ktruss_subgraph

**Comment by nickjcroucher** [comment]
Should this be added under a `--gpu-network` flag? Could try adding these functions one-by-one that way I suppose, once the big PR is merged.

**Comment by johnlees** [comment]
It's supposed to be completely interoperable with networkx (perhaps unfortunate now we've completely removed that), but I think a third GPU flag to enable this would be very sensible

**Comment by nickjcroucher** [comment]
So networkx-type code needs to be added back in? At least we can retrieve the code.

**Comment by johnlees** [comment]
Yeah. I think we'll keep it as graph tools, and just have functions which convert to/from cugraph, and then the time-consuming ones (cliques, network score) should be fairly small drop-ins
