### ISSUE TITLE
can we run poppunk on a population containing different species within the same genus 

### ISSUE THREAD

**Issue by mabouelk** [johnlees/PopPUNK#88]

**Comment by johnlees** [comment]
It depends on how diverse the genus is, and will likely need to adjust the k-mer length range away from the defaults as longer k-mers are likely to mismatch with a lot of diversity. I would run in mode `--create-db` with the option `--plot-fit 10` first to make sure you are getting reasonable straight line fits for your k-mer range, and adjust with `--min-k` and `--max-k` if not. 

After that, the first level clusters should be the species divides. You may need to attempt the fit iteratively to get these at the desired level of specificity.
