### ISSUE TITLE
Floating point exception

### ISSUE THREAD

**Issue by fasnicar** [johnlees/PopPUNK#96]
Hi all,

I wanted to try PopPUNK, but I'm getting the following error:
```
PopPUNK (POPulation Partitioning Using Nucleotide Kmers)
        (with backend: sketchlib v1.4.0
         sketchlib: /home/francesco/anaconda3/envs/poppunk-2.0.2/lib/python3.8/site-packages/pp_sketchlib.cpython-38-x86_64-linux-gnu.so)
Mode: Creating clusters from assemblies (create_db & fit_model)
Worst random match probability at 13-mers: 0.04
Sketching 128 genomes using 4 thread(s)
Writing sketches to file
Calculating random match chances using Monte Carlo
Calculating distances using 0 thread(s)
Floating point exception (core dumped)
```

The command is the one from the _Listeria monocytogenes_ quickstart tutorial:
```
poppunk --easy-run --r-files reference_list.txt --output lm_example --threads 4 --plot-fit 5 --min-k 13 --full-db
```

And the inputs are the 128 _Listeria monocytogenes_ genomes downloaded from [figshare](https://doi.org/10.6084/m9.figshare.7083389), prepared with the two commands provided in the tutorial:
```
tar xf listeria_example.tar.bz2
paste <(ls *.contigs_velvet.fa) <(ls *.contigs_velvet.fa) > reference_list.txt
```

Any help is appreciated.

Many thanks,
Francesco

**Comment by johnlees** [comment]
What version of PopPUNK are you running?. I guess this is v2.0.2, and you will need v2.1.0. Did you install via conda?
I think it's the case that I need to update the version available via to the newest version, which you can then upgrade to

**Comment by fasnicar** [comment]
Many thanks for your quick reply! Yes, I forgot to specify the version, as you said I installed the 2.0.2 from conda.
Many thanks if you can updated the conda package.

**Comment by johnlees** [comment]
I'm having trouble getting the new version on conda right away unfortunately. If you want to get this working now, could I suggest either:

- Installing the newest version of PopPUNK directly from this repo (either do a `git clone` of the repo and run `python poppunk-runner.py`; or run `setup.py install` after being cloned).
- Downgrade pp-sketchlib to v1.3.0

**Comment by fasnicar** [comment]
Dear John, many thanks for your suggestions.
I confirm I'm able to run PopPUNK 2.1.0, but I had to use pp-sketchlib to v1.4.0 as it wasn't working with version 1.3.0.

Many thanks,
Francesco
